create table if not exists public.visitors (
  id bigint generated by default as identity primary key,
  date date not null unique,
  count integer not null default 0 check (count >= 0),
  updated_at timestamptz not null default now()
);

create or replace function public.increment_visitor_count(p_date date default current_date)
returns table(today_count integer, total_count integer)
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.visitors(date, count)
  values (p_date, 1)
  on conflict (date)
  do update set
    count = public.visitors.count + 1,
    updated_at = now();

  return query
  select
    coalesce((select v.count from public.visitors v where v.date = p_date), 0)::integer as today_count,
    coalesce((select sum(v.count) from public.visitors v), 0)::integer as total_count;
end;
$$;

grant execute on function public.increment_visitor_count(date) to anon, authenticated;
grant select, insert, update on public.visitors to anon, authenticated;

do $$
begin
  if to_regclass('public.visitors_id_seq') is not null then
    grant usage, select on sequence public.visitors_id_seq to anon, authenticated;
  end if;
end;
$$;

alter table public.visitors enable row level security;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'visitors'
      and policyname = 'Public can read visitor counts'
  ) then
    create policy "Public can read visitor counts"
      on public.visitors
      for select
      to anon, authenticated
      using (true);
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'visitors'
      and policyname = 'Public can insert visitor counts'
  ) then
    create policy "Public can insert visitor counts"
      on public.visitors
      for insert
      to anon, authenticated
      with check (true);
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'visitors'
      and policyname = 'Public can update visitor counts'
  ) then
    create policy "Public can update visitor counts"
      on public.visitors
      for update
      to anon, authenticated
      using (true)
      with check (true);
  end if;
end;
$$;
